--- Provides localization handle lookups for native keybinding categories and event names.
--- This module maps keybinding identifiers to their display strings or localization handles.
---@class NativeKeybindingsTranslator
NativeKeybindingsTranslator = {}

-- Internal mapping of category names to their display strings
local _categoryStrings = {
  [""] = "h86fe2b0403a84fb7908f6bdf3ee17dd21e7f",
  ["CameraControls"] = "hbf47285d75054db8961a2bbd76e650fcd991",
  ["PhotoModeControls"] = "h726ccf29105d41538780a0a1b61bf3cab5f0",
  ["UI"] = "hd0c6191488c948b99d81f0cd66fc1ccb6a26",
  ["General"] = "h11c49d334a6d429eb1fa26da1379390a5333"
}

-- Internal mapping of event names to their display strings
local _eventStrings = {
  -- Camera Controls
  ["CameraForward"] = "h2d7144c5b0454e149411e2542ab303ae933b",
  ["CameraBackward"] = "h39a720e76b4141949a505be4a602a75d54ea",
  ["CameraLeft"] = "h7e26b3c3fa6a4606be5ba33fd622eb837e70",
  ["CameraRight"] = "h24831ad9f6ef40a5a98377fa56ee766d8f26",
  ["CameraZoomIn"] = "h5675f4200f7f46a2a2af47c66fa9ccac2221",
  ["CameraZoomOut"] = "hca0f71f6093a4bf695237cae5bd5a1badg51",
  ["CameraZoom"] = "Camera Zoom",
  ["CameraRotateLeft"] = "h1ce8fbd46d3a4f46acba57ed0a734bfa2ab5",
  ["CameraRotateRight"] = "h5563361ff2b744848871cdbaf12539c16c5b",
  ["CameraRotate"] = "Camera Rotate",
  ["CameraRotateMouseLeft"] = "Camera Rotate Mouse Left",
  ["CameraRotateMouseRight"] = "Camera Rotate Mouse Right",
  ["CameraToggleMouseRotate"] = "h1174c660801b4143acde0a6f1dfc2a6ed5g8",
  ["DefaultCameraPanCamera"] = "Default Camera Pan Camera",
  ["DefaultCameraSpecialPanCamera1"] = "Default Camera Special Pan Camera 1",
  ["DefaultCameraSpecialPanCamera2"] = "Default Camera Special Pan Camera 2",
  ["DefaultCameraToggleMouseRotation"] = "Default Camera Toggle Mouse Rotation",
  ["DefaultCameraCaptureInput"] = "Default Camera Capture Input",
  ["DefaultCameraLeft"] = "Default Camera Left",
  ["DefaultCameraRight"] = "Default Camera Right",
  ["DefaultCameraForward"] = "Default Camera Forward",
  ["DefaultCameraBackward"] = "Default Camera Backward",
  ["DefaultCameraUp"] = "Default Camera Up",
  ["DefaultCameraDown"] = "Default Camera Down",
  ["DefaultCameraZoomIn"] = "Default Camera Zoom In",
  ["DefaultCameraZoomOut"] = "Default Camera Zoom Out",
  ["DefaultCameraRotateLeft"] = "Default Camera Rotate Left",
  ["DefaultCameraRotateRight"] = "Default Camera Rotate Right",
  ["DefaultCameraRotateUp"] = "Default Camera Rotate Up",
  ["DefaultCameraRotateDown"] = "Default Camera Rotate Down",
  ["DefaultCameraMouseLeft"] = "Default Camera Mouse Left",
  ["DefaultCameraMouseRight"] = "Default Camera Mouse Right",
  ["DefaultCameraMouseUp"] = "Default Camera Mouse Up",
  ["DefaultCameraMouseDown"] = "Default Camera Mouse Down",
  ["DefaultCameraTopView"] = "Default Camera Top View",
  ["DefaultCameraLeftView"] = "Default Camera Left View",
  ["DefaultCameraFrontView"] = "Default Camera Front View",
  ["DefaultCameraSlow"] = "Default Camera Slow",
  ["DefaultCameraFast"] = "Default Camera Fast",
  ["CameraCenter"] = "Camera Center",
  ["FreeCameraToggleMouseRotate"] = "Free Camera Toggle Mouse Rotate",
  ["FreeCameraMoveForward"] = "Free Camera Move Forward",
  ["FreeCameraMoveBackward"] = "Free Camera Move Backward",
  ["FreeCameraMoveLeft"] = "Free Camera Move Left",
  ["FreeCameraMoveRight"] = "Free Camera Move Right",
  ["FreeCameraFoVInc"] = "Free Camera FoV Increase",
  ["FreeCameraFoVDec"] = "Free Camera FoV Decrease",
  ["FreeCameraSpeedInc"] = "Free Camera Speed Increase",
  ["FreeCameraSpeedDec"] = "Free Camera Speed Decrease",
  ["FreeCameraSpeedReset"] = "Free Camera Speed Reset",
  ["FreeCameraRotSpeedInc"] = "Free Camera Rotation Speed Increase",
  ["FreeCameraRotSpeedDec"] = "Free Camera Rotation Speed Decrease",
  ["FreeCameraRotateControllerLeft"] = "Free Camera Rotate Controller Left",
  ["FreeCameraRotateControllerRight"] = "Free Camera Rotate Controller Right",
  ["FreeCameraRotateControllerUp"] = "Free Camera Rotate Controller Up",
  ["FreeCameraRotateControllerDown"] = "Free Camera Rotate Controller Down",
  ["FreeCameraRotateMouseLeft"] = "Free Camera Rotate Mouse Left",
  ["FreeCameraRotateMouseRight"] = "Free Camera Rotate Mouse Right",
  ["FreeCameraRotateMouseUp"] = "Free Camera Rotate Mouse Up",
  ["FreeCameraRotateMouseDown"] = "Free Camera Rotate Mouse Down",
  ["FreeCameraHeightInc"] = "Free Camera Height Increase",
  ["FreeCameraHeightDec"] = "Free Camera Height Decrease",
  ["FreeCameraSlowdown"] = "Free Camera Slowdown",
  ["FreeCameraFreezeGameTime"] = "Free Camera Freeze Game Time",

  -- Photo mode
  ["PhotoModeCameraBackward"] = "Photo Mode Camera Backward",
  ["PhotoModeCameraForward"] = "Photo Mode Camera Forward",
  ["PhotoModeCameraLeft"] = "Photo Mode Camera Left",
  ["PhotoModeCameraRight"] = "Photo Mode Camera Right",
  ["PhotoModeCameraToggleMouseRotate"] = "Photo Mode Camera Toggle Mouse Rotate",
  ["PhotoModeCameraHeightInc"] = "Photo Mode Camera Height Increase",
  ["PhotoModeCameraHeightDec"] = "Photo Mode Camera Height Decrease",
  ["PhotoModeCameraRotateMouseRight"] = "Photo Mode Camera Rotate Mouse Right",
  ["PhotoModeCameraRotateMouseLeft"] = "Photo Mode Camera Rotate Mouse Left",
  ["PhotoModeCameraRotateMouseUp"] = "Photo Mode Camera Rotate Mouse Up",
  ["PhotoModeCameraRotateMouseDown"] = "Photo Mode Camera Rotate Mouse Down",
  ["PhotoModeCameraRotateRight"] = "Photo Mode Camera Rotate Right",
  ["PhotoModeCameraRotateLeft"] = "Photo Mode Camera Rotate Left",
  ["PhotoModeCameraRotateUp"] = "Photo Mode Camera Rotate Up",
  ["PhotoModeCameraRotateUpAlt"] = "Photo Mode Camera Rotate Up Alt",
  ["PhotoModeCameraRotateDown"] = "Photo Mode Camera Rotate Down",
  ["PhotoModeCameraRotateDownAlt"] = "Photo Mode Camera Rotate Down Alt",
  ["PhotoModeCameraTiltRight"] = "Photo Mode Camera Tilt Right",
  ["PhotoModeCameraTiltLeft"] = "Photo Mode Camera Tilt Left",

  -- Character Controls
  ["CharacterMoveForward"] = "h74811b458d7c4508a32237dc7e3efa173789",
  ["CharacterMoveBackward"] = "h5dfb2c27117d4b779116875a427ff373c18f",
  ["CharacterMoveLeft"] = "h7b47f1295b6d48d491e5bce102d5637f11cf",
  ["CharacterMoveRight"] = "h867a112c3e6e4ae2bbc52dd477dbf4e3b95e",
  ["Jump"] = "hb12f6c48442548e1b9e387a14d9a20aaee2c",
  ["ToggleSneak"] = "h7025fc893be6495088864712e05d0adaa889",
  ["Interact"] = "hdb227dc7309b42b885a9b133058c47aa5663",
  ["Shove"] = "h024c99f044774880a6a1a90dc1f1bcbfb56c",
  ["Throw"] = "h0956d399e7d54f3c9e52482048530abcf06d",

  -- UI Controls
  ["ToggleInventory"] = "h166a50bf762d4cd7a1d827184d336bb264df",
  ["ToggleCharacterOverview"] = "hab00d79972f3481784c6c31b1d5779f0c742",
  ["ToggleJournal"] = "h10c8d7eba5144bc4ac9ca09ff20f29e283af",
  ["ToggleMap"] = "h8745d6a103924a2fa748042b1c7b95734g00",
  ["ToggleSpells"] = "h70085eab331a4597bba1bfdcf6de0b5b8g23",
  ["ToggleCombatMode"] = "hd0e73646b7c14325ac1d7a7e2ad65f3c9ggd",
  ["ToggleWeaponSet"] = "ha67fb4a3797740c6b74aa406c9364064dd69",
  ["ToggleInGameMenu"] = "h9e7d63a517984acc84b5e64187cce82672d5",

  -- Common UI Actions
  ["UIAccept"] = "hf5e39ec5e1914d2a8f6a9ee6d6e888ed968e",
  ["UICancel"] = "h683a30d71c35413086cbd53bfd4f4e8da827",
  ["UILeft"] = "h579cabee5479438ab94dd3b8b47c66b70789",
  ["UIRight"] = "had916ada428d43119b088e53521f3beb99b3",
  ["UIUp"] = "h3ef3ea845c2e4902b8c4633a2c63209059g3",
  ["UIDown"] = "h85d3fde3585b4127b2ccfe271399b3a7a5ea",
  ["UITabNext"] = "h44a74f242dc842828ae26f5e91408b423def",
  ["UITabPrev"] = "h79de9dffb4604234a93e77eef26696835f1g",
  ["UILeftMouse"] = "UI Left Mouse",
  ["UIRightMouse"] = "UI Right Mouse",
  ["UIAddClass"] = "UI Add Class",
  ["UIDelete"] = "UI Delete",
  ["UIBack"] = "UI Back",
  ["UITakeAll"] = "UI Take All",
  ["UIEndTurn"] = "UI End Turn",
  ["UICancelEndTurn"] = "UI Cancel End Turn",
  ["UIEnterTurnBased"] = "UI Enter Turn-Based",
  ["UILeaveTurnBased"] = "UI Leave Turn-Based",
  ["UIFleeFromCombat"] = "UI Flee From Combat",
  ["UIRadialLeft"] = "UI Radial Left",
  ["UIRadialRight"] = "UI Radial Right",
  ["UIRadialUp"] = "UI Radial Up",
  ["UIRadialDown"] = "UI Radial Down",
  ["UIPinTooltip"] = "UI Pin Tooltip",
  ["UISkipDialog"] = "UI Skip Dialog",
  ["UIPhotoModeTakePicture"] = "UI Photo Mode Take Picture",
  ["UIToggleTadpolePowers"] = "UI Toggle Tadpole Powers",
  ["UIToggleAlchemy"] = "UI Toggle Alchemy",
  ["UIMove"] = "UI Move",
  ["UISelectionLeft"] = "UI Selection Left",
  ["UISelectionRight"] = "UI Selection Right",
  ["UISelectionUp"] = "UI Selection Up",
  ["UISelectionDown"] = "UI Selection Down",
  ["UISelectChar1"] = "UI Select Character 1",
  ["UISelectChar2"] = "UI Select Character 2",
  ["UISelectChar3"] = "UI Select Character 3",
  ["UISelectChar4"] = "UI Select Character 4",
  ["UISelectSlot0"] = "UI Select Slot 0",
  ["UISelectSlot1"] = "UI Select Slot 1",
  ["UISelectSlot2"] = "UI Select Slot 2",
  ["UISelectSlot3"] = "UI Select Slot 3",
  ["UISelectSlot4"] = "UI Select Slot 4",
  ["UISelectSlot5"] = "UI Select Slot 5",
  ["UISelectSlot6"] = "UI Select Slot 6",
  ["UISelectSlot7"] = "UI Select Slot 7",
  ["UISelectSlot8"] = "UI Select Slot 8",
  ["UISelectSlot9"] = "UI Select Slot 9",
  ["UISelectSlot11"] = "UI Select Slot 11",
  ["UISelectSlot12"] = "UI Select Slot 12",
  ["UICompareItems"] = "UI Compare Items",
  ["UIRequestTrade"] = "UI Request Trade",
  ["UIAddPoints"] = "UI Add Points",
  ["UIRemovePoints"] = "UI Remove Points",
  ["UIRefresh"] = "UI Refresh",
  ["UICreateLobby"] = "UI Create Lobby",
  ["UICreate"] = "UI Create",
  ["UIShowInfo"] = "UI Show Info",
  ["UIRename"] = "UI Rename",
  ["UIEnterCode"] = "UI Enter Code",
  ["UIFilter"] = "UI Filter",
  ["UIKickPlayer"] = "UI Kick Player",
  ["UIMutePlayer"] = "UI Mute Player",
  ["UIRenameLobby"] = "UI Rename Lobby",
  ["UIMoveChar"] = "UI Move Character",
  ["UIMapAddCustomMarker"] = "UI Map Add Custom Marker",
  ["UIMapRemoveCustomMarker"] = "UI Map Remove Custom Marker",
  ["UIMapMove"] = "UI Map Move",
  ["UIMapDown"] = "UI Map Down",
  ["UIMapUp"] = "UI Map Up",
  ["UIMapLeft"] = "UI Map Left",
  ["UIMapRight"] = "UI Map Right",
  ["UIMapZoomIn"] = "UI Map Zoom In",
  ["UIMapZoomOut"] = "UI Map Zoom Out",
  ["UIMapReset"] = "UI Map Reset",
  ["UIMapRemoveMarker"] = "UI Map Remove Marker",
  ["UIMapToggleWaypoints"] = "UI Map Toggle Waypoints",
  ["UIMapShowInJournal"] = "UI Map Show In Journal",
  ["UISwitchMode"] = "UI Switch Mode",
  ["UITradeBalance"] = "UI Trade Balance",
  ["UIMessageBoxA"] = "UI Message Box A",
  ["UIMiddleMouse"] = "UI Middle Mouse",
  ["UIMessageBoxB"] = "UI Message Box B",
  ["UIMessageBoxX"] = "UI Message Box X",
  ["UIMessageBoxY"] = "UI Message Box Y",
  ["UIInvite"] = "UI Invite",
  ["UIToggleTutorials"] = "UI Toggle Tutorials",
  ["UICopy"] = "UI Copy",
  ["UICut"] = "UI Cut",
  ["UIPaste"] = "UI Paste",
  ["UIEditTextBox"] = "UI Edit Text Box",
  ["UISelectAllText"] = "UI Select All Text",
  ["UIMarkWares"] = "UI Mark Wares",
  ["UISort"] = "UI Sort",
  ["UIToggleCharacterOverview"] = "UI Toggle Character Overview",
  ["UIDirectConnect"] = "UI Direct Connect",
  ["UIStartPoll"] = "UI Start Poll",
  ["UICallAllies"] = "UI Call Allies",
  ["UITogglePhotoMode"] = "UI Toggle Photo Mode",
  ["UITogglePhotoModeSecondary"] = "UI Toggle Photo Mode Secondary",
  ["UITogglePhotoPreview"] = "UI Toggle Photo Preview",
  ["UIMouseMove"] = "UI Mouse Move",
  ["UIArrowUp"] = "UI Arrow Up",
  ["UIArrowLeft"] = "UI Arrow Left",
  ["UIArrowRight"] = "UI Arrow Right",
  ["UIArrowDown"] = "UI Arrow Down",
  ["UIEnter"] = "UI Enter",
  ["UIPgUp"] = "UI Page Up",
  ["UIPgDn"] = "UI Page Down",
  ["UIBackspace"] = "UI Backspace",
  ["UITab"] = "UI Tab",
  ["UIBaseDelete"] = "UI Base Delete",
  ["UIHome"] = "UI Home",
  ["UIEnd"] = "UI End",
  ["UICtrl"] = "UI Control",
  ["UIAlt"] = "UI Alt",
  ["UIScroll"] = "UI Scroll",
  ["UIScrollUp"] = "UI Scroll Up",
  ["UIScrollDown"] = "UI Scroll Down",
  ["UIBaseCancel"] = "UI Base Cancel",

  -- Unknown/unsorted
  ["Unknown"] = "Unknown Event",
  ["KeyboardAny"] = "Keyboard Any",
  ["ControllerUnlinkedY"] = "Controller Unlinked Y",
  ["CharacterCreationRotateLeft"] = "Character Creation Rotate Left",
  ["CharacterCreationRotateRight"] = "Character Creation Rotate Right",
  ["CharacterCreationAccept"] = "Character Creation Accept",
  ["DragSingleToggle"] = "Drag Single Toggle",
  ["TogglePresentation"] = "Toggle Presentation",
  ["ToggleSummaryFocus"] = "Toggle Summary Focus",
  ["JumpToFromTab"] = "Jump To/From Tab",
  ["PartyManagement"] = "Party Management",
  ["PanelSelect"] = "Panel Select",
  ["SpeakerSelect"] = "Speaker Select",
  ["CycleCharactersNext"] = "Cycle Characters Next",
  ["CycleCharactersPrev"] = "Cycle Characters Previous",
  ["ClimbingToggle"] = "Climbing Toggle",
  ["DestructionToggle"] = "Destruction Toggle",
  ["HighlightCharacters"] = "Highlight Characters",
  ["ActionCancel"] = "Action Cancel",
  ["NextObject"] = "Next Object",
  ["Pause"] = "Pause",
  ["PrevObject"] = "Previous Object",
  ["QuickLoad"] = "Quick Load",
  ["QuickSave"] = "Quick Save",
  ["SkipVideo"] = "Skip Video",
  ["SplitItemToggle"] = "Split Item Toggle",
  ["RotateItemLeft"] = "Rotate Item Left",
  ["RotateItemRight"] = "Rotate Item Right",
  ["TeleportPlayer"] = "Teleport Player",
  ["TeleportParty"] = "Teleport Party",
  ["ToggleDualWielding"] = "Toggle Dual Wielding",
  ["ToggleSplitscreen"] = "Toggle Splitscreen",
  ["ToggleInfo"] = "Toggle Info",
  ["ToggleInputMode"] = "Toggle Input Mode",
  ["CancelSelectorMode"] = "Cancel Selector Mode",
  ["ToggleReactions"] = "Toggle Reactions",
  ["ToggleSpellsEnd"] = "Toggle Spells End",
  ["ToggleInspiration"] = "Toggle Inspiration",
  ["ToggleRestPanel"] = "Toggle Rest Panel",
  ["ToggleGroupMode"] = "Toggle Group Mode",
  ["ToggleGroupStealth"] = "Toggle Group Stealth",
  ["ToggleManualTurnBasedMode"] = "Toggle Manual Turn-Based Mode",
  ["TogglePartyCharacterView"] = "Toggle Party Character View",
  ["GroupingSelect"] = "Grouping Select",
  ["GroupingSplit"] = "Grouping Split",
  ["GroupingConfirm"] = "Grouping Confirm",
  ["ContextMenu"] = "Context Menu",
  ["ShortRest"] = "Short Rest",
  ["Combine"] = "Combine",
  ["ToggleTacticalCamera"] = "Toggle Tactical Camera",
  ["ShowWorldTooltips"] = "Show World Tooltips",
  ["ExpandTooltip"] = "Expand Tooltip",
  ["ShowSneakCones"] = "Show Sneak Cones",
  ["ToggleDialogPrivacy"] = "Toggle Dialog Privacy",
  ["Ping"] = "Ping",
  ["CopyVersionToClipboard"] = "Copy Version To Clipboard",
  ["ConnectivityMenu"] = "Connectivity Menu",
  ["ToggleDialogueHistory"] = "Toggle Dialogue History",
  ["WidgetToggleOutput"] = "Widget Toggle Output",
  ["WidgetToggleEffectStats"] = "Widget Toggle Effect Stats",
  ["Action1"] = "Action 1",
  ["WidgetScreenshot"] = "Widget Screenshot",
  ["WidgetScreenshotVideo"] = "Widget Screenshot Video",
  ["WidgetToggleOptions"] = "Widget Toggle Options",
  ["WidgetToggleStats"] = "Widget Toggle Stats",
  ["WidgetToggleDebugConsole"] = "Widget Toggle Debug Console",
  ["WidgetToggleVFXDebug"] = "Widget Toggle VFX Debug",
  ["WidgetToggleGraphicsDebug"] = "Widget Toggle Graphics Debug",
  ["WidgetToggleDevComments"] = "Widget Toggle Developer Comments",
  ["WidgetButtonTab"] = "Widget Button Tab",
  ["WidgetButtonLeft"] = "Widget Button Left",
  ["ControllerUnlinkedBack"] = "Controller Unlinked Back",
  ["WidgetButtonRight"] = "Widget Button Right",
  ["WidgetButtonUp"] = "Widget Button Up",
  ["WidgetButtonDown"] = "Widget Button Down",
  ["WidgetButtonHome"] = "Widget Button Home",
  ["WidgetButtonEnd"] = "Widget Button End",
  ["WidgetButtonDelete"] = "Widget Button Delete",
  ["WidgetButtonBackSpace"] = "Widget Button Backspace",
  ["WidgetButtonEnter"] = "Widget Button Enter",
  ["WidgetButtonEscape"] = "Widget Button Escape",
  ["WidgetButtonPageUp"] = "Widget Button Page Up",
  ["ControllerUnlinkedStart"] = "Controller Unlinked Start",
  ["WidgetButtonPageDown"] = "Widget Button Page Down",
  ["WidgetButtonSpace"] = "Widget Button Space",
  ["WidgetButtonA"] = "Widget Button A",
  ["WidgetButtonC"] = "Widget Button C",
  ["WidgetButtonV"] = "Widget Button V",
  ["WidgetButtonX"] = "Widget Button X",
  ["WidgetButtonY"] = "Widget Button Y",
  ["WidgetButtonZ"] = "Widget Button Z",
  ["WidgetUndo"] = "Widget Undo",
  ["WidgetRedo"] = "Widget Redo",
  ["ControllerUnlinkedA"] = "Controller Unlinked A",
  ["WidgetCut"] = "Widget Cut",
  ["WidgetCopy"] = "Widget Copy",
  ["WidgetPaste"] = "Widget Paste",
  ["WidgetScrollUp"] = "Widget Scroll Up",
  ["WidgetScrollDown"] = "Widget Scroll Down",
  ["WidgetMouseMotion"] = "Widget Mouse Motion",
  ["WidgetMouseLeft"] = "Widget Mouse Left",
  ["WidgetMouseRight"] = "Widget Mouse Right",
  ["ControllerUnlinkedB"] = "Controller Unlinked B",
  ["ControllerUnlinkedX"] = "Controller Unlinked X",
}

--- Gets the display string for a category name.
---@param categoryName string The category name to look up
---@return string The display string for the category, or a default string if not found
function NativeKeybindingsTranslator.GetCategoryString(categoryName)
  if not categoryName then return _categoryStrings[""] end
  return _categoryStrings[categoryName] or _categoryStrings[""]
end

--- Gets the display string for an event name.
---@param eventName string The event name to look up
---@return string The display string for the event, or the original name if not found
function NativeKeybindingsTranslator.GetEventString(eventName)
  if not eventName then return "" end
  local str = _eventStrings[eventName]

  if not str then
    str = eventName:gsub("([A-Z])", " %1"):gsub("^%s+", "")
    _eventStrings[eventName] = str
  end

  local locString = Ext.Loca.GetTranslatedString(str)
  if locString and locString ~= "" then return locString end

  return str
end

return NativeKeybindingsTranslator
