RequireFiles("Shared/Helpers/", {
    "Table/_Init",
    "Events/_Init",
    "VC/_Init",
    "CooldownHelper",
    "Keybindings/_Init",
    "LoadOrderHealthCheck/_Init",
    "PathValidator",
    "Validators/_Init",
    "Config",
    "Printer",
    "Color",
    "Fallback",
    "Preprocessing/_Init",
    "MCM/_Init",
})
